# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-12-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'abc', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='movie',
            field=models.ManyToManyField(to='movies.Movies'),
        ),
    ]
